baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = "Fuloido's Blog"
theme = 'archie'
copyright = "© Fuloido"

# TODO: Comment System
# disqusShortname = "yourDisqusShortname"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    favicon = "/favicon.png"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/fuloido"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
